export const TABLE_CELL_EDITING_CHANGED = 'TABLE_CELL_EDITING_CHANGED';

export const TABLE_CELL_VALUES_CHANGE = 'TABLE_CELL_VALUES_CHANGE';

export const TABLE_CELL_FIELDS_CHANGE = 'TABLE_CELL_FIELDS_CHANGE';

export const TABLE_CELL_CLICK = 'TABLE_CELL_CLICK';

export const TABLE_KEY_DOWN = 'TABLE_KEY_DOWN';

export const TABLE_STOP_ACTIVE = 'TABLE_STOP_ACTIVE';

export const TABLE_ARROW_KEY_CODE_MAP = {
  LEFT: 37,
  UP: 38,
  RIGHT: 39,
  DOWN: 40,
  NEXT: -999,
};
