export const TABLE_CELL_EDITING_CHANGED = 'TABLE_CELL_EDITING_CHANGED';

export const TABLE_CELL_VALUES_CHANGE = 'TABLE_CELL_VALUES_CHANGE';

export const TABLE_CELL_FIELDS_CHANGE = 'TABLE_CELL_FIELDS_CHANGE';
