import { LEG_FIELD } from '@/constants/common';
import { SmartTable, InputNumber } from '@/containers';
import { Modal, Button } from 'antd';
import _ from 'lodash';
import React, { memo, useState, useEffect } from 'react';
import FormItem from 'antd/lib/form/FormItem';
import useLifecycles from 'react-use/lib/useLifecycles';
import { PAGE_SIZE } from '@/constants/component';
import { trdTradeSettleablePaged } from '@/services/trade-service';

const d = {
  page: [
    {
      bookName: 'jtniu',
      tradeId: '24354321',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-06-27',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-06-04T04:51:17.670Z',
      updatedAt: '2019-06-04T04:51:17.765Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '24354321_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_EUROPEAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'SELLER',
            exerciseType: 'EUROPEAN',
            underlyerInstrumentId: '600030.SH',
            initialSpot: 18.13,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-04',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'PUT',
            notionalAmount: 1e3,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-04',
            effectiveDate: '2019-06-04',
            counterpartyCode: '3',
            premiumType: 'PERCENT',
            premium: 0.018729,
            frontPremium: 0.018729,
            minimumPremium: 0,
          },
          counterPartyCode: '3',
          counterPartyName: '3',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
        {
          bookName: null,
          positionId: '24354321_1',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_EUROPEAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'SELLER',
            exerciseType: 'EUROPEAN',
            underlyerInstrumentId: '600030.SH',
            initialSpot: 18.13,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-04',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'PUT',
            notionalAmount: 1e3,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-04',
            effectiveDate: '2019-06-04',
            counterpartyCode: '3',
            premiumType: 'PERCENT',
            premium: 0.018729,
            frontPremium: 0.018729,
            minimumPremium: 0,
          },
          counterPartyCode: '3',
          counterPartyName: '3',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'options_lu_0418',
      tradeId: '65346tr',
      trader: 'lidan',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-06-25',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-06-04T03:17:29.296Z',
      updatedAt: '2019-06-04T03:17:29.306Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '65346tr_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 43.7564,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-04',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 653,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-04',
            effectiveDate: '2019-06-04',
            counterpartyCode: '大联邦',
            premiumType: 'PERCENT',
            premium: 65.43,
            frontPremium: 65.77,
            minimumPremium: 0.34,
          },
          counterPartyCode: '大联邦',
          counterPartyName: '大联邦',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'options_lu_0424',
      tradeId: '524twrefsdf',
      trader: 'lidan',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-06-04',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '111',
      salesName: '111',
      salesCommission: 0,
      createdAt: '2019-06-04T02:43:51.139Z',
      updatedAt: '2019-06-04T02:43:51.147Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '524twrefsdf_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 25,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-04',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 54,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-04',
            effectiveDate: '2019-06-04',
            counterpartyCode: '0002',
            premiumType: 'PERCENT',
            premium: 0.54,
            frontPremium: 0.77,
            minimumPremium: 0.23,
          },
          counterPartyCode: '0002',
          counterPartyName: '0002',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'test',
      tradeId: 'twresdf',
      trader: 'lidan',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-06-04',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-06-04T02:33:43.466Z',
      updatedAt: '2019-06-04T02:33:43.498Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: 'twresdf_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000059.SZ',
            initialSpot: 6.46,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-04',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 43,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-04',
            effectiveDate: '2019-06-04',
            counterpartyCode: '大联邦',
            premiumType: 'PERCENT',
            premium: 0.43,
            frontPremium: 0.55,
            minimumPremium: 0.12,
          },
          counterPartyCode: '大联邦',
          counterPartyName: '大联邦',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'test',
      tradeId: '1111111',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-06-03',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-06-03T08:37:59.782Z',
      updatedAt: '2019-06-03T08:37:59.870Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '1111111_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_EUROPEAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'EUROPEAN',
            underlyerInstrumentId: '000333.SZ',
            initialSpot: 50.12,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-03',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 1e6,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-03',
            effectiveDate: '2019-06-03',
            counterpartyCode: '大联邦',
            premiumType: 'PERCENT',
            premium: 0.02,
            frontPremium: 0.04,
            minimumPremium: 0.02,
          },
          counterPartyCode: '大联邦',
          counterPartyName: '大联邦',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: '567',
      tradeId: 'qeqwe21',
      trader: 'wuyongbin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-06-03',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '同余小哥',
      salesName: '同余小哥',
      salesCommission: 0,
      createdAt: '2019-06-03T05:50:30.880Z',
      updatedAt: '2019-06-03T05:50:30.897Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: 'qeqwe21_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000036.SZ',
            initialSpot: 7.32,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-07-03',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 111111,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-07-03',
            effectiveDate: '2019-06-03',
            counterpartyCode: '123',
            premiumType: 'PERCENT',
            premium: 0.11,
            frontPremium: 0.22,
            minimumPremium: 0.11,
          },
          counterPartyCode: '123',
          counterPartyName: '123',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: '41234124334',
      tradeId: '22222',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-29',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '同余小哥',
      salesName: '同余小哥',
      salesCommission: 0,
      createdAt: '2019-05-29T12:16:28.686Z',
      updatedAt: '2019-05-29T12:16:28.688Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '22222_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 26.04,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-28',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'PUT',
            notionalAmount: 2,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-28',
            effectiveDate: '2019-05-29',
            counterpartyCode: '毅威',
            premiumType: 'PERCENT',
            premium: 0.02,
            frontPremium: 0.04,
            minimumPremium: 0.02,
          },
          counterPartyCode: '毅威',
          counterPartyName: '毅威',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'options3',
      tradeId: 'aszxvcz',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-27',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-05-27T07:19:09.727Z',
      updatedAt: '2019-05-27T07:19:09.763Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: 'aszxvcz_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000429.SZ',
            initialSpot: 4.255,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-26',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 12,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-26',
            effectiveDate: '2019-05-27',
            counterpartyCode: '大联邦',
            premiumType: 'PERCENT',
            premium: 0.12,
            frontPremium: 0.44,
            minimumPremium: 0.32,
          },
          counterPartyCode: '大联邦',
          counterPartyName: '大联邦',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'options2',
      tradeId: 'afsdfasdf',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-27',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '111',
      salesName: '111',
      salesCommission: 0,
      createdAt: '2019-05-27T06:29:28.627Z',
      updatedAt: '2019-05-27T06:29:28.630Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: 'afsdfasdf_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 26.235,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-26',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 54,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-26',
            effectiveDate: '2019-05-27',
            counterpartyCode: '0002',
            premiumType: 'PERCENT',
            premium: 0.03505,
            frontPremium: 0.26505,
            minimumPremium: 0.23,
          },
          counterPartyCode: '0002',
          counterPartyName: '0002',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: '567',
      tradeId: '523rfsdg',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-28',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '111',
      salesName: '111',
      salesCommission: 0,
      createdAt: '2019-05-27T06:28:40.943Z',
      updatedAt: '2019-05-27T06:28:40.945Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '523rfsdg_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000059.SZ',
            initialSpot: 6.595,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-26',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 54,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-26',
            effectiveDate: '2019-05-27',
            counterpartyCode: '0002',
            premiumType: 'PERCENT',
            premium: 0.34,
            frontPremium: 0.77,
            minimumPremium: 0.43,
          },
          counterPartyCode: '0002',
          counterPartyName: '0002',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'bookTest',
      tradeId: '432',
      trader: 'admin',
      comment: '非线性互换',
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-27',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '111',
      salesName: '111',
      salesCommission: 0,
      createdAt: '2019-05-27T06:26:31.208Z',
      updatedAt: '2019-05-27T06:26:31.222Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '432_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 26.265,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-26',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 123,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-26',
            effectiveDate: '2019-05-27',
            counterpartyCode: '0002',
            premiumType: 'PERCENT',
            premium: 0.03505,
            frontPremium: 0.15505,
            minimumPremium: 0.12,
          },
          counterPartyCode: '0002',
          counterPartyName: '0002',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'options_lu_0418',
      tradeId: 'srfdf423',
      trader: 'admin',
      comment: '线性互换',
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-28',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '同余小哥',
      salesName: '同余小哥',
      salesCommission: 0,
      createdAt: '2019-05-27T06:07:04.106Z',
      updatedAt: '2019-05-27T06:07:04.137Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: 'srfdf423_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 26.15,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-26',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 23,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-26',
            effectiveDate: '2019-05-27',
            counterpartyCode: '毅威',
            premiumType: 'PERCENT',
            premium: 0.23,
            frontPremium: 0.46,
            minimumPremium: 0.23,
          },
          counterPartyCode: '毅威',
          counterPartyName: '毅威',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'tongyu',
      tradeId: '24234',
      trader: 'admin',
      comment: '期权',
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-01',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-05-24T13:58:31.431Z',
      updatedAt: '2019-05-24T13:58:31.449Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '24234_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'OPEN',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'SELLER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000036.SZ',
            initialSpot: 7.065,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-23',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 234234,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-23',
            effectiveDate: '2019-05-24',
            counterpartyCode: '大联邦',
            premiumType: 'PERCENT',
            premium: 2342.34,
            frontPremium: 4684.68,
            minimumPremium: 2342.34,
          },
          counterPartyCode: '大联邦',
          counterPartyName: '大联邦',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'bookTest',
      tradeId: '3234243242432',
      trader: 'admin',
      comment: '期权',
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-24',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '销售000',
      salesName: '销售000',
      salesCommission: 0,
      createdAt: '2019-05-24T11:14:06.613Z',
      updatedAt: '2019-05-24T11:14:06.640Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '3234243242432_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'AMEND',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'COMMODITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: 'RB1910',
            initialSpot: 3839.5,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-23',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'PUT',
            notionalAmount: 2e3,
            notionalAmountType: 'LOT',
            underlyerMultiplier: 1e1,
            expirationDate: '2019-06-23',
            effectiveDate: '2019-05-24',
            counterpartyCode: '大联邦',
            premiumType: 'PERCENT',
            premium: 0.12,
            frontPremium: 0.25,
            minimumPremium: 0.13,
          },
          counterPartyCode: '大联邦',
          counterPartyName: '大联邦',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
    {
      bookName: 'options_lu_0424',
      tradeId: '3123',
      trader: 'admin',
      comment: null,
      tradeStatus: 'LIVE',
      tradeDate: '2019-05-21',
      partyCode: 'empty',
      partyName: 'empty',
      salesCode: '同余小哥',
      salesName: '同余小哥',
      salesCommission: 0,
      createdAt: '2019-05-24T08:13:12.864Z',
      updatedAt: '2019-05-24T08:13:12.866Z',
      portfolioNames: null,
      positions: [
        {
          bookName: null,
          positionId: '3123_0',
          userLoginId: null,
          quantity: null,
          lcmEventType: 'AMEND',
          productType: 'VANILLA_AMERICAN',
          assetClass: 'EQUITY',
          asset: {
            direction: 'BUYER',
            exerciseType: 'AMERICAN',
            underlyerInstrumentId: '000049.SZ',
            initialSpot: 14,
            strikeType: 'PERCENT',
            strike: 1,
            specifiedPrice: 'CLOSE',
            settlementDate: '2019-06-23',
            term: 3e1,
            annualized: true,
            daysInYear: 365,
            participationRate: 1,
            optionType: 'CALL',
            notionalAmount: 23,
            notionalAmountType: 'CNY',
            underlyerMultiplier: 1,
            expirationDate: '2019-06-23',
            effectiveDate: '2019-05-24',
            counterpartyCode: '123',
            premiumType: 'PERCENT',
            premium: 0.12,
            frontPremium: 0.44,
            minimumPremium: 0.32,
          },
          counterPartyCode: '123',
          counterPartyName: '123',
          positionAccountCode: 'empty',
          positionAccountName: 'empty',
          counterPartyAccountCode: 'empty',
          counterPartyAccountName: 'empty',
          createdAt: null,
          updatedAt: null,
        },
      ],
    },
  ],
  totalCount: 172,
};

const Settlement = memo<any>(props => {
  const { modalVisible, setModalVisible } = props;
  const [tableData, setTableData] = useState([]);
  const [pagination, setPagination] = useState({
    page: 0,
    total: 0,
    pageSize: PAGE_SIZE,
  });
  const [loading, setLoading] = useState(false);

  const fetch = async () => {
    // const { error, data = {} } = await trdTradeSettleablePaged(pagination);
    const error = false;
    const data = d;
    const { page, totalCount } = data;
    setTableData(page);
    setPagination(pre => ({ ...pre, total: totalCount }));
  };

  useEffect(
    () => {
      if (!modalVisible) return;
      fetch();
    },
    [modalVisible]
  );

  return (
    <Modal
      destroyOnClose={true}
      title="批量结算"
      width={1300}
      visible={modalVisible}
      onCancel={() => {
        setModalVisible(false);
      }}
    >
      <SmartTable
        onCellFieldsChange={(props, fields) => {
          // setTableData(pre => {
          //   return pre.map(item => {
          //     if (item.id )
          //   })
          // })
        }}
        rowKey="id"
        dataSource={tableData}
        rowSelection={{}}
        loading={loading}
        scroll={_.isEmpty(tableData) ? undefined : { x: 2000 }}
        columns={[
          {
            title: '交易簿',
            dataIndex: LEG_FIELD.BOOK_NAME,
          },
          {
            title: '交易ID',
            dataIndex: LEG_FIELD.TRADE_ID,
          },
          {
            title: '交易日',
            dataIndex: LEG_FIELD.TRADE_DATE,
          },
          {
            title: '买/卖',
            dataIndex: LEG_FIELD.DIRECTION,
          },
          {
            title: '涨/跌',
            dataIndex: LEG_FIELD.OPTION_TYPE,
          },
          {
            title: '期权类型',
            dataIndex: LEG_FIELD.PRODUCT_TYPE,
          },
          {
            title: '行权价',
            align: 'right',
            dataIndex: LEG_FIELD.STRIKE,
          },
          {
            title: '标的物',
            fixed: 'right',
            width: 150,
            dataIndex: LEG_FIELD.UNDERLYER_INSTRUMENT_ID,
          },
          {
            title: '结算方式',
            fixed: 'right',
            width: 150,
            dataIndex: LEG_FIELD.SPECIFIED_PRICE,
          },
          {
            title: '标的物结算价格',
            fixed: 'right',
            align: 'right',
            width: 150,
            editable: true,
            dataIndex: LEG_FIELD.UNDERLYER_INSTRUMENT_PRICE,
            render: (val, record, index, { form, editing }) => {
              return (
                <FormItem>
                  {form.getFieldDecorator()(<InputNumber autoFocus={true} editing={editing} />)}
                </FormItem>
              );
            },
          },
          {
            title: '结算金额',
            fixed: 'right',
            align: 'right',
            width: 150,
            editable: true,
            dataIndex: LEG_FIELD.SETTLE_AMOUNT,
            render: (val, record, index, { form, editing }) => {
              return (
                <FormItem>
                  {form.getFieldDecorator()(<InputNumber autoFocus={true} editing={editing} />)}
                </FormItem>
              );
            },
          },
          {
            title: '结算状态',
            fixed: 'right',
            width: 150,
            dataIndex: LEG_FIELD.SETTLE_STATUS,
          },
        ]}
      />
    </Modal>
  );
});

export default Settlement;
