import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  Barrier,
  BarrierType,
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  InitialSpot,
  KnockDirection,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  ObservationType,
  OptionType,
  ParticipationRate,
  Premium,
  PremiumType,
  Rebate,
  RebateType,
  RebateUnit,
  SettlementDate,
  SpecifiedPrice,
  Strike,
  StrikeType,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';
import { setRuleLeg } from './rules';

export const BarrierUnAnnual = pipeLeg({
  name: '单鲨 - 非年化',
  type: LEG_TYPE_MAP.BARRIER_UNANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: false,
  columnDefs: [
    Direction,
    OptionType,
    UnderlyerInstrumentId,
    UnderlyerMultiplier,
    InitialSpot,
    StrikeType,
    Strike,
    KnockDirection,
    SpecifiedPrice,
    SettlementDate,
    ParticipationRate,
    NotionalAmountType,
    NotionalAmount,
    EffectiveDate,
    ExpirationDate,
    RebateUnit,
    RebateType,
    Rebate,
    BarrierType,
    Barrier,
    PremiumType,
    Premium,
    ObservationType,
  ],
});
