import { ILegType } from '@/constants/legColDefs';
import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  BarrierType,
  DaysInYear,
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  HighBarrier,
  InitialSpot,
  LowBarrier,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  ParticipationRate,
  Payment,
  PaymentType,
  Premium,
  PremiumType,
  SettlementDate,
  SpecifiedPrice,
  Term,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';

export const ConcavaUnAnnual: ILegType = pipeLeg({
  name: '二元凹式 - 非年化',
  type: LEG_TYPE_MAP.CONCAVA_UNANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: false,
  columnDefs: [
    BarrierType,
    DaysInYear,
    Direction,
    EffectiveDate,
    ExpirationDate,
    HighBarrier,
    InitialSpot,
    LowBarrier,
    NotionalAmount,
    NotionalAmountType,
    ParticipationRate,
    Payment,
    PaymentType,
    Premium,
    PremiumType,
    SettlementDate,
    SpecifiedPrice,
    Term,
    UnderlyerInstrumentId,
    UnderlyerMultiplier,
  ],
});
