import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  BarrierType,
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  HighBarrier,
  HighParticipationRate,
  HighRebate,
  HighStrike,
  InitialSpot,
  LowBarrier,
  LowParticipationRate,
  LowRebate,
  LowStrike,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  ObservationType,
  Premium,
  PremiumType,
  RebateType,
  SettlementDate,
  SpecifiedPrice,
  StrikeType,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';

export const DoubleSharkFinUnAnnual = pipeLeg({
  name: '双鲨 - 非年化',
  type: LEG_TYPE_MAP.DOUBLE_SHARK_FIN_UNANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: false,
  columnDefs: [
    Direction,
    UnderlyerMultiplier,
    UnderlyerInstrumentId,
    InitialSpot,
    SpecifiedPrice,
    SettlementDate,
    LowParticipationRate,
    HighParticipationRate,
    NotionalAmount,
    NotionalAmountType,
    EffectiveDate,
    ExpirationDate,
    StrikeType,
    LowStrike,
    HighStrike,
    RebateType,
    LowRebate,
    HighRebate,
    BarrierType,
    LowBarrier,
    HighBarrier,
    PremiumType,
    Premium,

    ObservationType,
  ],
});
