import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  BarrierType,
  DaysInYear,
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  HighBarrier,
  HighParticipationRate,
  HighRebate,
  HighStrike,
  InitialSpot,
  LowBarrier,
  LowParticipationRate,
  LowRebate,
  LowStrike,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  ObservationType,
  Premium,
  PremiumType,
  RebateType,
  SettlementDate,
  SpecifiedPrice,
  StrikeType,
  Term,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';

export const DoubleSharkFinAnnual = pipeLeg({
  name: '双鲨 - 年化',
  type: LEG_TYPE_MAP.DOUBLE_SHARK_FIN_ANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: true,
  columnDefs: [
    Direction,
    UnderlyerMultiplier,
    UnderlyerInstrumentId,
    InitialSpot,
    SpecifiedPrice,
    SettlementDate,
    Term,
    DaysInYear,
    LowParticipationRate,
    HighParticipationRate,
    NotionalAmount,
    NotionalAmountType,
    EffectiveDate,
    ExpirationDate,
    StrikeType,
    LowStrike,
    HighStrike,
    RebateType,
    LowRebate,
    HighRebate,
    BarrierType,
    LowBarrier,
    HighBarrier,
    PremiumType,
    Premium,
    FrontPremium,
    MinimumPremium,
    ObservationType,
  ],
});
