import { ILegType } from '@/constants/legColDefs';
import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  DaysInYear,
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  HighPayment,
  HighStrike,
  InitialSpot,
  LowPayment,
  LowStrike,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  OptionType,
  ParticipationRate,
  PaymentType,
  Premium,
  PremiumType,
  SettlementDate,
  SpecifiedPrice,
  StrikeType,
  Term,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';

export const DoubleDigitalAnnual: ILegType = pipeLeg({
  name: '三层阶梯 - 年化',
  type: LEG_TYPE_MAP.DOUBLE_DIGITAL_ANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: true,
  columnDefs: [
    Direction,
    UnderlyerMultiplier,
    UnderlyerInstrumentId,
    InitialSpot,
    SpecifiedPrice,
    SettlementDate,
    Term,
    DaysInYear,
    ParticipationRate,
    NotionalAmount,
    NotionalAmountType,
    EffectiveDate,
    ExpirationDate,
    PaymentType,
    LowPayment,
    HighPayment,
    PremiumType,
    Premium,
    FrontPremium,
    MinimumPremium,
    OptionType,
    StrikeType,
    LowStrike,
    HighStrike,
  ],
});
