import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  InitialSpot,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  ParticipationRate1,
  ParticipationRate2,
  Premium,
  PremiumType,
  SettlementDate,
  SpecifiedPrice,
  Strike1,
  Strike2,
  Strike3,
  Strike4,
  StrikeType,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';

export const EagleUnAnnual = pipeLeg({
  name: '鹰式 - 非年化',
  type: LEG_TYPE_MAP.EAGLE_UNANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: false,
  columnDefs: [
    Direction,
    UnderlyerMultiplier,
    UnderlyerInstrumentId,
    InitialSpot,
    SpecifiedPrice,
    SettlementDate,
    ParticipationRate1,
    ParticipationRate2,
    NotionalAmount,
    NotionalAmountType,
    EffectiveDate,
    ExpirationDate,
    StrikeType,
    Strike1,
    Strike2,
    Strike3,
    Strike4,
    PremiumType,
    Premium,
  ],
});
