import { ILegType } from '@/constants/legColDefs';
import { ASSET_CLASS_MAP, LEG_TYPE_MAP } from '../common';
import {
  DaysInYear,
  Direction,
  EffectiveDate,
  ExpirationDate,
  FrontPremium,
  InitialSpot,
  MinimumPremium,
  NotionalAmount,
  NotionalAmountType,
  OptionType,
  ParticipationRate,
  Payment1,
  Payment2,
  Payment3,
  PaymentType,
  Premium,
  PremiumType,
  SettlementDate,
  SpecifiedPrice,
  Strike1,
  Strike2,
  Strike3,
  StrikeType,
  Term,
  UnderlyerInstrumentId,
  UnderlyerMultiplier,
} from './common/common';
import { pipeLeg } from './common/pipeLeg';

export const TripleDigitalUnAnnual: ILegType = pipeLeg({
  name: '四层阶梯 - 非年化',
  type: LEG_TYPE_MAP.TRIPLE_DIGITAL_UNANNUAL,
  assetClass: ASSET_CLASS_MAP.EQUITY,
  isAnnualized: false,
  columnDefs: [
    Direction,
    UnderlyerMultiplier,
    UnderlyerInstrumentId,
    InitialSpot,
    SpecifiedPrice,
    SettlementDate,
    Term,
    DaysInYear,
    ParticipationRate,
    NotionalAmount,
    NotionalAmountType,
    EffectiveDate,
    ExpirationDate,
    PaymentType,
    PremiumType,
    Premium,
    OptionType,
    StrikeType,
    Strike1,
    Strike2,
    Strike3,
    Payment1,
    Payment2,
    Payment3,
  ],
});
