export const BASE_FORM_FIELDS = {
  LEGALNAME: 'legalName',
  LEGALREPRESENTATIVE: 'legalRepresentative',
  ADDRESS: 'address',
  WARRANTOR: 'warrantor',
  WARRANTORADDRESS: 'warrantorAddress',
  TRADEPHONE: 'tradePhone',
  TRADEEMAIL: 'tradeEmail',
  DDRESS_CASCADER: 'DDRESS_CASCADER',
  MASTERAGREEMENTID: 'masterAgreementId',
  CONTACT: 'contact',
  TRUSTOREMAIL: 'trustorEmail',
  AUTHORIZEEXPIRYDATE: 'authorizeExpiryDate',
  SIGNAUTHORIZERNAME: 'signAuthorizerName',
  SIGNAUTHORIZERIDNUMBER: 'signAuthorizerIdNumber',
  SIGNAUTHORIZERIDEXPIRYDATE: 'signAuthorizerIdExpiryDate',
  TRADEAUTHORIZERNAME: 'tradeAuthorizerName',
  TRADEAUTHORIZERIDNUMBER: 'tradeAuthorizerIdNumber',
  TRADEAUTHORIZERIDEXPIRYDATE: 'tradeAuthorizerIdExpiryDate',
  TRADEAUTHORIZERPHONE: 'tradeAuthorizerPhone',
  PRODUCTNAME: 'productName',
  PRODUCTCODE: 'productCode',
  PRODUCTTYPE: 'productType',
  RECORDNUMBER: 'recordNumber',
  PRODUCTFOUNDDATE: 'productFoundDate',
  PRODUCTEXPIRINGDATE: 'productExpiringDate',
  FUNDMANAGER: 'fundManager',
};
